# Generated by Django 6.0.4 on 2026-04-26 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_created_at_user_updated_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Seller',
        ),
    ]
