services:
  - type: web
    name: nazmul-ecommerce-api
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn config.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings.production
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: DATABASE_URL
        fromDatabase:
          name: nazmul-ecommerce-db
          property: connectionString
      - key: ALLOWED_HOSTS
        value: .onrender.com
      - key: PYTHON_VERSION
        value: 3.12.0

databases:
  - name: nazmul-ecommerce-db
    plan: free
    databaseName: nazmul_ecommerce
    ipAllowList: []
