# Generated by Django 6.0.4 on 2026-04-26 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_inventoryreservation_alter_inventory_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='attribute_hash',
            field=models.CharField(default='e350da752a2b66839febdc3421a4d2f66c8dc3058d6777528542a513bc055e97', max_length=64),
        ),
    ]
